name: "Check Pull Request"
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Dependency Review"
        uses: actions/dependency-review-action@v3

  rome-ci:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - uses: rome/setup-rome@v0.4
        with:
          version: latest 

      - name: "Run rome ci ."
        run: rome ci .
