# This workflow automatically update gh-pages when main/README.md is changed

name: Update GH Pages

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [README.md]

jobs:
  update-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: gh-pages
          
      - name: update gh-pages/README.md from main
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout origin/main README.md

      - uses: oven-sh/setup-bun@v2
      - name: transform README.md to index.md using mark2jek
        run: bunx mark2jek README.md new=index.md

      - name: Commit and Push files
        run: |
          git add README.md index.md
          git commit -m "[github-actions] update GH pages from main"
          git push
